version: '2'
services: 
    rabbitmq:
        image: "rabbitmq:3.6-management"
        ports:
            - "15672:15672"
        links:
            - consumer
            - producer
    consumer:
        build: ./consumer
        volumes: 
            - .:/consumer      
    producer:
        build: ./producer
        volumes: 
            - .:/producer
       